version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=False
      - HOST=0.0.0.0
      - PORT=5000
    restart: always
    # Add volumes if you need persistent data
    # volumes:
    #   - ./data:/app/data
