version: '3'

services:
  # Option 1: Using SQLite with volume
  app-sqlite:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=false
      - SQLITE_PATH=/data/app.db
    volumes:
      - sqlite-data:/data
    restart: unless-stopped


volumes:
  sqlite-data:
