"""Add TimeChangeRequest model

Revision ID: 2fbc8e130466
Revises: 
Create Date: 2025-04-01 12:14:38.051996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbc8e130466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plan', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('share_link',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_study_plan_share_link')
        batch_op.create_unique_constraint('uq_study_plan_share_link', ['share_link'])
    
    op.create_table('time_change_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposed_start_time', sa.DateTime(), nullable=False),
    sa.Column('proposed_end_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('study_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_change_request')
    
    with op.batch_alter_table('study_plan', schema=None) as batch_op:
        batch_op.drop_constraint('uq_study_plan_share_link', type_='unique')
        batch_op.create_index('ix_study_plan_share_link', ['share_link'], unique=1)
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('share_link',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
