"""Add feedback model

Revision ID: 936c1e803eca
Revises: 
Create Date: 2025-04-01 16:07:07.175018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936c1e803eca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('subject', sa.String(length=200), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), default=sa.func.current_timestamp()),
        sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('study_plan', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('share_link',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_study_plan_share_link')
        batch_op.create_unique_constraint('uq_study_plan_share_link', ['share_link'])
        batch_op.drop_column('location_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('uq_study_plan_share_link', type_='unique')
        batch_op.create_index('ix_study_plan_share_link', ['share_link'], unique=1)
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('share_link',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    op.drop_table('feedback')
    # ### end Alembic commands ###
